### ISSUE TITLE
Functionality Question

### ISSUE THREAD

**Issue by OpenSourceDistilling** [iloveicedgreentea/GPM-to-Spotify#6]
Great idea for this project. Thanks for doing it for the open-source community. 

I have a few questions about what's transferred from GMP to Spotify. 

Does this transfer:
1) Playlist
2) Artists
3) Albums

GPM has a 'Songs' section in the library, Spotify does not. Does this get transferred somehow or left out? 

It appears that some services only transfer playlists but I'm looking for all 3 items above. Please let me know, I am eager to make the switch to Spotify. 

Again, thanks for all your hard work. I appreciate it!

**Comment by iloveicedgreentea** [comment]
Hey sorry just seeing this now. I wrote this to transfer both my thumbed up music and playlists, playlists being the most important to me. It should transfer your playlists and also thumbed up songs which will translate to a liked song in spotify, as well as creating the playlists in spotify. 

For albums, not sure, I don't think so. You would have to create a playlist from the album first.

**Comment by effleurager** [comment]
I've created a PR which adds another script to transfer albums, based on the existing code. Give it a try @OpenSourceDistilling

**Comment by iloveicedgreentea** [comment]
Item 3 is solved with #7
